version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: gamerconnect-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: GamerConnect
      MYSQL_USER: gameruser
      MYSQL_PASSWORD: gamerpass
    volumes:
      - ./gamerconnect.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  api:
    build: .
    container_name: gamerconnect-api
    ports:
      - "3000:3000"
    depends_on:
      - db